sockets: fix compilation on illumos
introduced in f3526e58848fc48baf375ca42aa23d0d18dafefa

    sockets/unix_socket_nolinux.go:19:20: undefined: syscall.SysctlUint32
    sockets/unix_socket_nolinux.go:21:20: undefined: syscall.SysctlUint32
    sockets/unix_socket_nolinux.go:25:20: undefined: syscall.SysctlUint32

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>